app:
  baseUrl: https://backstage-k8s.maksonlee.com

backend:
  baseUrl: https://backstage-k8s.maksonlee.com
  cors:
    origin: https://backstage-k8s.maksonlee.com
    credentials: true

  database:
    connection:
      host: backstage-postgres

auth:
  providers:
    oidc:
      production:
        clientId: backstage-k8s

kubernetes:
  serviceLocatorMethod:
    type: multiTenant

  clusterLocatorMethods:
    - type: config
      clusters:
        - name: in-cluster
          url: https://kubernetes.default.svc
          authProvider: serviceAccount
          skipTLSVerify: false
          skipMetricsLookup: false
