apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-env
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backstage-env
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: backstage/prod
