apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - postgres.yaml
  - homelab-backstage.yaml
  - backstage-k8s-rbac.yaml

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:
  - name: backstage-k8s-config
    files:
      - app-config.k8s.yaml=app-config.k8s.yaml
