apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  provider:
    vault:
      server: 'https://vault.maksonlee.com'
      path: 'secret'
      version: 'v2'
      auth:
        kubernetes:
          mountPath: 'kubernetes'
          role: 'eso-backstage'
          serviceAccountRef:
            name: 'eso-vault'
            audiences:
              - vault
